version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: backend/logs/info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: backend/logs/errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: backend/logs/debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [console]
  propagate: false

loggers:
  backend:
    level: DEBUG
    handlers:
      [info_file_handler, error_file_handler, debug_file_handler, console]
    propagate: false # children (backend.*) propagate to this parent; we stop here to avoid root duplication
